repos:
  - repo: local
    hooks:
      - id: commitizen
        name: Commitizen check
        entry: cz
        args: ['check', '--commit-msg-file', '.git/COMMIT_EDITMSG']
        pass_filenames: false
        language: system
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.327
    hooks:
      - id: pyright

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
